# Configuration for Release Drafter - https://github.com/toolmantim/release-drafter

name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: ':rocket: Enhancement'
    label: 'Type: Feature'

  - title: ':bug: Bug Fix'
    label: 'Type: Bug'

  - title: ':memo: Documentation'
    label: 'Type: Documentation'

  - title: ':nail_care: Refactor'
    label: 'Type: Refactor'

  - title: ':house: Internal'
    label: 'Type: Internal'

  - title: ':wrench: Tooling'
    label: 'Type: Tooling'

  - title: ':package: Dependencies'
    label: 'Type: Dependencies'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
template: |
  $CHANGES
  ***
  ### Contributors 🦄
  Thank you $CONTRIBUTORS for the contributions! 🏆
  ***
