import { readdir, readFile } from "fs/promises"
import { join } from "path"

import matter from "gray-matter"

import type { VideoCardData, VideoData } from "@/lib/types"
import type { VideoFrontmatter } from "@/lib/interfaces"

import videosManifest from "@/data/generated/videos.json"

import { CONTENT_DIR, DEFAULT_LOCALE } from "@/lib/constants"

import { getVideoThumbnails } from "@/lib/data"

// Build-time caches for the individual video page (getVideoData), which still
// reads from public/content during static generation.
const videoDataCache = new Map<string, VideoData>()
let slugsCache: string[] | null = null

/**
 * Resolve the absolute path to a video's index.md for a given locale.
 * English: public/content/videos/{slug}/index.md
 * Translated: public/content/translations/{locale}/videos/{slug}/index.md
 */
function videoPath(slug: string, locale: string): string {
  return join(
    process.cwd(),
    CONTENT_DIR,
    locale === DEFAULT_LOCALE ? "" : `translations/${locale}`,
    `videos/${slug}/index.md`
  )
}

/**
 * Read and parse a video's index.md file for a given slug and locale.
 * Returns the full frontmatter and markdown body content.
 *
 * Results are cached per slug+locale to avoid redundant reads during
 * static generation (generateStaticParams, generateMetadata, and the
 * page component all call this for the same slug).
 *
 * For non-English locales, metadata (youtubeId, duration, etc.) is always
 * read from the English source. Title and description are overridden from
 * the translated file if available.
 */
export async function getVideoData(
  slug: string,
  locale: string = DEFAULT_LOCALE
): Promise<VideoData> {
  const cacheKey = `${locale}:${slug}`
  const cached = videoDataCache.get(cacheKey)
  if (cached) return cached

  // Always read English source for full metadata.
  // gray-matter has a global content-keyed cache that returns a shallow copy
  // (`data` shared by reference), so we spread to avoid mutating the cached
  // object — otherwise overriding title/description below leaks across locales.
  const enPath = videoPath(slug, DEFAULT_LOCALE)
  const enRaw = await readFile(enPath, "utf-8")
  const enParsed = matter(enRaw)
  const frontmatter = { ...enParsed.data } as VideoFrontmatter

  // gray-matter auto-converts YAML dates to Date objects; coerce back to string
  if ((frontmatter.uploadDate as unknown) instanceof Date) {
    frontmatter.uploadDate = (frontmatter.uploadDate as unknown as Date)
      .toISOString()
      .split("T")[0]
  }
  let content = enParsed.content

  // For non-English locales, try to read translated title/description
  if (locale !== DEFAULT_LOCALE) {
    try {
      const localePath = videoPath(slug, locale)
      const localeRaw = await readFile(localePath, "utf-8")
      const localeParsed = matter(localeRaw)

      if (typeof localeParsed.data.title === "string") {
        frontmatter.title = localeParsed.data.title
      }
      if (typeof localeParsed.data.description === "string") {
        frontmatter.description = localeParsed.data.description
      }
      // Use translated body if available
      if (localeParsed.content.trim()) {
        content = localeParsed.content
      }
    } catch {
      // Translated file not found -- use English (already loaded)
    }
  }

  const result = { slug, content, frontmatter }
  videoDataCache.set(cacheKey, result)
  return result
}

/**
 * Get all video slugs by scanning the content/videos directory.
 * Used only by the individual video page (build-time SSG).
 * Results are cached for the duration of the build.
 */
export async function getVideoSlugs(): Promise<string[]> {
  if (slugsCache) return slugsCache

  const videosDir = join(process.cwd(), CONTENT_DIR, "videos")
  const entries = await readdir(videosDir, { withFileTypes: true })
  slugsCache = entries.filter((e) => e.isDirectory()).map((e) => e.name)
  return slugsCache
}

/**
 * Get all videos for the gallery hub from the precompiled manifest, merging
 * runtime-fetched thumbnails. The manifest is generated by
 * src/scripts/build-content-manifests so the hub doesn't need public/content
 * available in the deployed function.
 */
export async function getVideos(
  locale: string = DEFAULT_LOCALE
): Promise<VideoCardData[]> {
  const manifest = videosManifest as Record<string, VideoCardData[]>
  const entries = manifest[locale] ?? manifest[DEFAULT_LOCALE] ?? []
  const thumbnailMap = await getVideoThumbnails().catch(() => null)

  return entries.map((entry) => ({
    ...entry,
    thumbnailUrl: thumbnailMap?.[entry.slug] || "",
  }))
}
