import { readFileSync } from "fs"

import { expect, test } from "@playwright/test"

import chains from "@/data/chains"

/**
 * `networks.ts` is read as text rather than imported: it imports logo images, which
 * resolve through the bundler and not in Node.
 *
 * These check the parts of it a human types and a machine can verify. The block explorer
 * offered in search used to be a second, generated list that had to be regenerated by
 * hand; the data lives beside each network now, so the risk moved from "someone forgets
 * to run a script" to "someone mistypes a short name", which is what this catches.
 */
const SOURCE = readFileSync("src/data/networks/networks.ts", "utf-8")

interface Entry {
  chainName: string
  prefix?: string
  brand?: string
  routes: string[]
}

const entries: Entry[] = [
  ...SOURCE.matchAll(
    // `ethereumNetworkData` sits at two spaces of indent, the rollups at four.
    /chainName: "([^"]+)",[\s\S]{0,900}?searchExplorer: \{([\s\S]*?)\n\s{2,6}\},/g
  ),
].map(([, chainName, body]) => ({
  chainName,
  prefix: /prefix: "([^"]+)"/.exec(body)?.[1],
  brand: /brand: "([^"]+)"/.exec(body)?.[1],
  routes: [...body.matchAll(/(search|address|tx): "([^"]+)"/g)].map(
    (m) => m[1]
  ),
}))

test.describe("network explorer data", () => {
  test("finds an explorer for every network on the L2 page", () => {
    // Guards the parser too: a shape change would otherwise yield nothing and pass.
    expect(entries.length).toBeGreaterThanOrEqual(11)
    expect(entries.map((e) => e.chainName)).toContain("Ethereum Mainnet")
    expect(entries.map((e) => e.chainName)).toContain("Starknet")
    for (const { chainName, brand, routes } of entries) {
      expect(brand, `${chainName} has no explorer brand`).toBeTruthy()
      // Either one route that resolves anything, or an address/tx pair. Never half.
      const shape = routes.includes("search")
        ? routes.length === 1
        : routes.includes("address") && routes.includes("tx")
      expect(shape, `${chainName} routes: ${routes.join()}`).toBe(true)
    }
  })

  test("every prefix matches the short name chainid.network reports", () => {
    // EIP-3770 short names are not ours to invent. A typo would simply stop matching,
    // silently, so it is checked against `chains.ts` -- itself generated from the same
    // registry and refreshed weekly, so an upstream rename turns this red.
    for (const { chainName, prefix } of entries) {
      if (!prefix) continue
      const chain = chains.find((c) => c.name === chainName)
      if (!chain) continue // non-EVM, so not in chains.ts
      expect(
        prefix,
        `${chainName} declares prefix "${prefix}", chains.ts says "${chain.shortName}"`
      ).toBe(chain.shortName)
    }
  })

  test("non-EVM networks declare it, since their values are a different shape", () => {
    const starknet = SOURCE.slice(SOURCE.indexOf('chainName: "Starknet"'))
    expect(starknet.slice(0, 400)).toContain('addressFormat: "starknet"')
    // And carry no EIP-3770 prefix, which only exists for EVM chains.
    expect(
      entries.find((e) => e.chainName === "Starknet")?.prefix
    ).toBeUndefined()
  })
})
