import { execSync } from "child_process"
import fs from "fs"
import path from "path"

import {
  BLOCKSCOUT_CHAINS_ENDPOINT,
  CHAINID_NETWORK_ENDPOINT,
  EXPLORER_NETWORKS,
} from "../lib/constants"

interface ChainListEntry {
  chainId: number
  name: string
  shortName: string
}

interface BlockscoutChain {
  name: string
  explorers?: { url: string; hostedBy: string }[]
}

/**
 * Regenerates src/data/explorers.ts.
 *
 * Two sources, joined on chain id: chainid.network supplies the EIP-3770 `shortName`
 * that users would actually type, and Blockscout's registry supplies the explorer URL.
 * Neither alone is enough -- chainid.network lists explorers we don't want to endorse,
 * and Blockscout's registry has no notion of short names.
 */
const fetchJson = async <T>(url: string): Promise<T> => {
  const response = await fetch(url)
  if (!response.ok)
    throw new Error(`Failed to fetch ${url}: ${response.status}`)
  return response.json()
}

const buildExplorers = async () => {
  const [chainList, blockscout] = await Promise.all([
    fetchJson<ChainListEntry[]>(CHAINID_NETWORK_ENDPOINT),
    fetchJson<Record<string, BlockscoutChain>>(BLOCKSCOUT_CHAINS_ENDPOINT),
  ])

  const byId = new Map(chainList.map((chain) => [chain.chainId, chain]))
  // Insertion order is the row order, so this must stay an ordered literal.
  const explorers: Record<string, { name: string; url: string; icon: string }> =
    {}

  for (const { chainId, icon } of EXPLORER_NETWORKS) {
    const chain = byId.get(chainId)
    const entry = blockscout[String(chainId)]
    if (!chain?.shortName || !entry) {
      console.warn(`  skipped ${chainId}: no shortName or not on Blockscout`)
      continue
    }
    // Prefer an instance Blockscout hosts; several chains run the same software on
    // their own domain, which is still the explorer that chain's users expect.
    const explorer =
      entry.explorers?.find((e) => e.hostedBy === "blockscout") ??
      entry.explorers?.[0]
    if (!explorer) {
      console.warn(`  skipped ${chainId}: no explorer listed`)
      continue
    }
    explorers[chain.shortName.toLowerCase()] = {
      // chainid.network's name, not Blockscout's -- it matches the `ChainName`
      // spelling the rest of the codebase uses ("Arbitrum One", not "Arbitrum One Nitro").
      name: chain.name,
      url: explorer.url.replace(/\/$/, ""),
      icon,
    }
  }

  const outPath = path.join(process.cwd(), "src/data/explorers.ts")
  const header = `// Generated by src/scripts/update-explorers.ts -- do not edit by hand.
// Keys are EIP-3770 chain short names, the prefix a user types before an address.`
  fs.writeFileSync(
    outPath,
    `${header}\nconst explorers = ${JSON.stringify(explorers, null, 2)} as const\n\nexport default explorers\n`,
    "utf-8"
  )
  console.log(
    `Generated ${outPath} with ${Object.keys(explorers).length} networks`
  )
  execSync(`npx prettier ${outPath} --write`)
}

buildExplorers()
