import { execSync } from "child_process"
import fs from "fs"
import path from "path"

import {
  BLOCKSCOUT_CHAINS_ENDPOINT,
  CHAINID_NETWORK_ENDPOINT,
} from "../lib/constants"

import { readFeaturedNetworks } from "./typesense/featured-networks"

interface ChainListEntry {
  chainId: number
  shortName: string
}

interface BlockscoutChain {
  explorers?: { url: string; hostedBy: string }[]
}

/**
 * Regenerates src/data/explorers.ts.
 *
 * Which networks appear is decided by `src/data/networks/networks.ts` -- the same file
 * `/layer-2/networks` renders from -- so the two cannot drift. Everything else is joined
 * on chain id: chainid.network supplies the EIP-3770 short name a user would type as a
 * prefix, and Blockscout's registry supplies the explorer URL. Neither is ours to
 * maintain, and typing either by hand invites a mismatch that fails silently.
 *
 * A network with no entry here is not necessarily unsupported: Starknet and Zircuit are
 * handled by their own explorers in constants.ts. `explorer-coverage.spec.ts` is what
 * makes sure a network is covered one way or the other.
 */
const fetchJson = async <T>(url: string): Promise<T> => {
  const response = await fetch(url)
  if (!response.ok)
    throw new Error(`Failed to fetch ${url}: ${response.status}`)
  return response.json()
}

const buildExplorers = async () => {
  const [chainList, blockscout] = await Promise.all([
    fetchJson<ChainListEntry[]>(CHAINID_NETWORK_ENDPOINT),
    fetchJson<Record<string, BlockscoutChain>>(BLOCKSCOUT_CHAINS_ENDPOINT),
  ])
  const shortNames = new Map(chainList.map((c) => [c.chainId, c.shortName]))

  // Insertion order is the row order, so this stays an ordered literal.
  const explorers: Record<string, { name: string; url: string; icon: string }> =
    {}

  for (const network of readFeaturedNetworks()) {
    const { chainId, name, icon, chainName } = network
    if (!chainId) {
      console.warn(`  skipped ${chainName}: not EVM, no chain id`)
      continue
    }
    const shortName = shortNames.get(chainId)
    const entry = blockscout[String(chainId)]
    if (!shortName || !entry) {
      console.warn(`  skipped ${chainName}: no short name or not on Blockscout`)
      continue
    }
    // Prefer an instance Blockscout hosts; several chains run the same software on their
    // own domain, which is still the explorer that chain's users expect.
    const explorer =
      entry.explorers?.find((e) => e.hostedBy === "blockscout") ??
      entry.explorers?.[0]
    if (!explorer) {
      console.warn(`  skipped ${chainName}: no explorer listed`)
      continue
    }
    explorers[shortName.toLowerCase()] = {
      // The nickname the L2 page shows, so search and the page agree.
      name,
      url: explorer.url.replace(/\/$/, ""),
      icon,
    }
  }

  const outPath = path.join(process.cwd(), "src/data/explorers.ts")
  const header = `// Generated by src/scripts/update-explorers.ts -- do not edit by hand.
// Networks come from src/data/networks/networks.ts; keys are EIP-3770 chain short names,
// the prefix a user types before an address.`
  fs.writeFileSync(
    outPath,
    `${header}\nconst explorers = ${JSON.stringify(explorers, null, 2)} as const\n\nexport default explorers\n`,
    "utf-8"
  )
  console.log(
    `Generated ${outPath} with ${Object.keys(explorers).length} networks`
  )
  execSync(`npx prettier ${outPath} --write`)
}

buildExplorers()
