import { execFileSync } from "node:child_process"
import { writeFileSync } from "node:fs"

import type { UpgradeStore } from "@/data/upgrades/types"

export const GENERATED_PATH = "src/data/upgrades/generated.ts"

/**
 * No upstream commit is recorded in the file. Stamping one would make the
 * output differ on every upstream commit even when the data is identical, so
 * `git diff --exit-code` could no longer be used to tell "stale or hand-edited"
 * from "upstream moved". Provenance belongs in the sync's PR body and run log.
 */
const HEADER = (repo: string) =>
  `// Generated by \`pnpm sync-upgrades\` from ${repo}.
// DO NOT EDIT — hand edits are overwritten by the next sync, and CI fails on
// any diff this script would produce.
`

export const render = (store: UpgradeStore, repo: string): string =>
  `${HEADER(repo)}
import type { UpgradeStore } from "./types"

export const generated = ${JSON.stringify(store, null, 2)} satisfies UpgradeStore
`

/** Prettier runs here so a fresh render is byte-comparable with the commit. */
export const write = (path: string, next: string): void => {
  writeFileSync(path, next)
  execFileSync("pnpm", ["exec", "prettier", "--write", path], {
    stdio: "ignore",
  })
}
