import { writeFileSync } from "node:fs"
import { format, resolveConfig } from "prettier"

import type { UpgradeStore } from "@/data/upgrades/types"

export const GENERATED_PATH = "src/data/upgrades/generated.ts"

/**
 * No upstream commit is recorded in the file. Stamping one would make the
 * output differ on every upstream commit even when the data is identical, so
 * `git diff --exit-code` could no longer be used to tell "stale or hand-edited"
 * from "upstream moved". Provenance belongs in the sync's PR body and run log.
 */
const HEADER = (repo: string) =>
  `// Generated by \`pnpm sync-upgrades\` from ${repo}.
// DO NOT EDIT — the weekly sync overwrites this file, so a hand edit survives
// until Friday and then disappears.
`

export const render = (store: UpgradeStore, repo: string): string =>
  `${HEADER(repo)}
import type { UpgradeStore } from "./types"

export const generated = ${JSON.stringify(store, null, 2)} satisfies UpgradeStore
`

/** Formats in memory and writes once, so a prettier failure never touches disk. */
export const write = async (path: string, next: string): Promise<void> => {
  const config = await resolveConfig(path)
  const formatted = await format(next, { ...config, filepath: path })
  writeFileSync(path, formatted)
}
