name: Suggest a Layer 2
description: Suggest a Layer 2 to list on ethereum.org
title: Suggest a Layer 2
labels: ["product 🧰"]
body:
  - type: markdown
    attributes:
      value: |
        Before suggesting a layer 2, make sure you've read [our listing policy](https://ethereum.org/contributing/adding-layer-2s/).
  - type: markdown
    attributes:
      value: |
        Only continue with the issue if your layer 2 meets the criteria listed there.
  - type: markdown
    attributes:
      value: |
        If it does, complete the following information which we need to accurately list the layer 2.
  - type: markdown
    id: project_info
    attributes:
      value: "## Project info"
  - type: input
    id: layer_2_name
    attributes:
      label: Name
      description: Please provide the official name of the layer 2 project
    validations:
      required: true
  - type: textarea
    id: layer_2_logo
    attributes:
      label: Logo
      description: |
        Please provide an SVG or hi-res transparent PNG
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: layer_2_description
    attributes:
      label: Description
      description: Please provide a 1-2 sentence (240 character max) of the layer 2 project
    validations:
      required: true
  - type: input
    id: layer_2_website
    attributes:
      label: Website
      description: Please provide a URL tot he website for the layer 2 project
    validations:
      required: true
  - type: input
    id: layer_2_developer_documentation
    attributes:
      label: Developer documentation
      description: Please provide a URL to the developer documentation for the layer 2 project
    validations:
      required: true
  - type: input
    id: layer_2_l2beat
    attributes:
      label: L2BEAT page
      description: Please provide a link to the layer 2s page on L2BEAT
    validations:
      required: true
  - type: textarea
    id: layer_2_open_source
    attributes:
      label: Is the project open source?
      description: If yes, please provide a link to the repository, if no, put N/A
    validations:
      required: true
  - type: textarea
    id: layer_2_category
    attributes:
      label: What category of layer 2 is it?
      description: Please provide some information on the implementation of the layer 2 project
    validations:
      required: true
  - type: textarea
    id: layer_2_data_availability
    attributes:
      label: Does the layer 2 use Ethereum Mainnet for data availability?
      description: Please provide proof that the layer 2 uses Ethereum for data availability
    validations:
      required: true
  - type: textarea
    id: layer_2_bridges
    attributes:
      label: Which bridges are used to onboard users?
      description: Please provide some information on how to bridge assets on the layer 2 network
    validations:
      required: true
  - type: textarea
    id: layer_2_exchanges
    attributes:
      label: Which exchanges offer support for the project?
      description: If there is exchange support for deposits or withdrawals, please provide information for this
  - type: input
    id: layer_2_dapp_ecosystem
    attributes:
      label: Link to dapp ecosystem (if applicable)
      description: "Please provide a link to the dapp ecosystem. (ex: https://portal.arbitrum.io/, https://www.optimism.io/apps)"
  - type: input
    id: layer_2_token_contract_list
    attributes:
      label: Token contract list (if applicable)
      description: Since assets will likely have a new address on the layer 2 network, if there is a token list resource available please share
  - type: input
    id: layer_2_live_date
    attributes:
      label: What date did the project go live?
      description: Please provide proof to substantiate the date
    validations:
      required: true
  - type: input
    id: layer_2_fork
    attributes:
      label: Is this project a fork? If yes, which project was forked?
      description: Please provide information about if this project is a fork
  - type: textarea
    id: layer_2_wallets
    attributes:
      label: What wallets support this layer 2?
      description: Please list wallets that support this layer 2 network
  - type: textarea
    id: layer_2_connect
    attributes:
      label: How can users and/or developers connect too this layer 2 network?
      description: What is the public RPC information for the network? (RPC URL, Chain ID, Currency Symbol)
  - type: textarea
    id: layer_2_audit
    attributes:
      label: Has this project undergone an external security audit and/or a bug bounty?
      description: Please provide a link to a report or repo for any audits or bug bounties. If you haven't been audited but think your layer 2 should be listed anyway, explain here
  - type: textarea
    id: layer_2_users
    attributes:
      label: Has the project sustained its users over time?
      description: Please provide supporting information such as TVL history, transaction statistics, and whether known companies or projects use it.
  - type: dropdown
    id: layer_2_active_maintained
    attributes:
      label: Is there an active team developing the project?
      options:
        - "Yes"
        - "No"
  - type: textarea
    id: layer_2_block_explorer
    attributes:
      label: Is there a block explorer?
      description: Are there block explorers for the network? Please share URLs.
  - type: checkboxes
    id: layer_2_work_on
    attributes:
      label: Would you like to work on this issue?
      options:
        - label: "Yes"
          required: false
        - label: "No"
          required: false
    validations:
      required: true
