/**
 * Contributors Utility
 *
 * Accesses pre-computed contributor data from JSON file generated
 * by the prebuild script. Optionally merges with Crowdin contributors
 * for translated content.
 */

import type { FileContributor, Lang } from "@/lib/types"

import {
  convertToFileContributorFromCrowdin,
  getCrowdinContributors,
} from "@/lib/utils/crowdin"
import { getLocaleTimestamp } from "@/lib/utils/time"

import { CONTENT_DIR, DEFAULT_LOCALE } from "@/lib/constants"

// Type for the pre-computed contributor data
interface ContributorEntry {
  contributors: FileContributor[]
  lastUpdated: string
}

type ContentContributors = Record<string, ContributorEntry>

// Import pre-computed contributor data
// This file is generated by scripts/prebuild/generate-contributors.ts
let contributorsData: ContentContributors = {}

// Try to load the pre-computed data
// Falls back to empty object if not available (first build)
try {
  // Dynamic import at module load time
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  contributorsData = require("@/data/content-contributors.json")
} catch {
  console.warn(
    "Content contributors data not found. Run prebuild:contributors first."
  )
}

/**
 * Get the file path key for looking up contributor data
 */
function getContributorKey(slug: string, locale: string): string {
  if (locale === DEFAULT_LOCALE) {
    return `${CONTENT_DIR}/${slug}/index.md`
  }
  return `${CONTENT_DIR}/translations/${locale}/${slug}/index.md`
}

/**
 * Get contributors for a markdown file.
 *
 * For English content: Returns GitHub contributors from pre-computed data.
 * For translated content: Merges Crowdin contributors (translators) with
 * GitHub contributors from the English source.
 *
 * @param slug - Content slug (e.g., "about" or "developers/docs/accounts")
 * @param locale - Locale code (e.g., "en", "es", "zh")
 * @returns Object with contributors array and lastUpdated timestamp
 */
export async function getContributors(
  slug: string,
  locale: string
): Promise<{
  contributors: FileContributor[]
  lastUpdated: string
}> {
  // Get English contributors from pre-computed data
  const englishKey = getContributorKey(slug, DEFAULT_LOCALE)
  const englishData = contributorsData[englishKey]

  const githubContributors = englishData?.contributors ?? []
  const lastUpdated = englishData?.lastUpdated ?? new Date().toISOString()

  // For English content, just return GitHub contributors
  if (locale === DEFAULT_LOCALE) {
    return {
      contributors: githubContributors,
      lastUpdated,
    }
  }

  // For translated content, merge with Crowdin contributors
  try {
    const crowdinContributors = getCrowdinContributors(
      `${CONTENT_DIR}/${slug}/index.md`,
      locale as Lang
    )

    // Convert Crowdin contributors to FileContributor format
    const convertedCrowdinContributors =
      convertToFileContributorFromCrowdin(crowdinContributors)

    // Merge: Crowdin contributors first (translators), then GitHub contributors
    const mergedContributors = [
      ...convertedCrowdinContributors,
      ...githubContributors,
    ]

    // Remove duplicates by login
    const uniqueContributors = mergedContributors.reduce<FileContributor[]>(
      (acc, contributor) => {
        if (!acc.some((c) => c.login === contributor.login)) {
          acc.push(contributor)
        }
        return acc
      },
      []
    )

    return {
      contributors: uniqueContributors,
      lastUpdated,
    }
  } catch (error) {
    // If Crowdin lookup fails, just return GitHub contributors
    console.warn(`Failed to get Crowdin contributors for ${slug}:`, error)
    return {
      contributors: githubContributors,
      lastUpdated,
    }
  }
}

/**
 * Get contributors synchronously (GitHub only, no Crowdin merge)
 *
 * Useful when async operations aren't possible.
 */
export function getContributorsSync(slug: string): {
  contributors: FileContributor[]
  lastUpdated: string
} {
  const key = getContributorKey(slug, DEFAULT_LOCALE)
  const data = contributorsData[key]

  return {
    contributors: data?.contributors ?? [],
    lastUpdated: data?.lastUpdated ?? new Date().toISOString(),
  }
}

/**
 * Format the last updated date for display
 *
 * @param isoDate - ISO date string
 * @param locale - Display locale for formatting
 * @returns Formatted date string (e.g., "January 15, 2024")
 */
export function formatLastUpdated(isoDate: string, locale: string): string {
  return getLocaleTimestamp(locale as Lang, isoDate)
}
