// Generated by `pnpm sync-upgrades` from ethereum/forkcast.
// DO NOT EDIT — the weekly sync overwrites this file, so a hand edit survives
// until Friday and then disappears.

import type { UpgradeStore } from "./types"

export const generated = {
  "the-merge": {
    slug: "the-merge",
    name: "The Merge",
    status: "live",
    mainnetTarget: {
      when: {
        year: 2022,
        month: 9,
        day: 15,
      },
      confirmed: true,
    },
    milestones: [
      {
        kind: "mainnet",
        when: {
          year: 2022,
          month: 9,
          day: 15,
        },
        status: "complete",
      },
    ],
    eips: [],
    sourceUrl: "https://forkcast.org/upgrade/the-merge",
  },
  shapella: {
    slug: "shapella",
    name: "Shapella",
    status: "live",
    mainnetTarget: {
      when: {
        year: 2023,
        month: 4,
        day: 12,
      },
      confirmed: true,
    },
    milestones: [
      {
        kind: "mainnet",
        when: {
          year: 2023,
          month: 4,
          day: 12,
        },
        status: "complete",
      },
    ],
    eips: [],
    sourceUrl: "https://forkcast.org/upgrade/shapella",
  },
  dencun: {
    slug: "dencun",
    name: "Dencun",
    status: "live",
    mainnetTarget: {
      when: {
        year: 2024,
        month: 3,
        day: 13,
      },
      confirmed: true,
    },
    milestones: [
      {
        kind: "mainnet",
        when: {
          year: 2024,
          month: 3,
          day: 13,
        },
        status: "complete",
      },
    ],
    eips: [
      {
        id: 4844,
        status: "included",
        networking: false,
        decidedAt: null,
      },
    ],
    sourceUrl: "https://forkcast.org/upgrade/dencun",
  },
  pectra: {
    slug: "pectra",
    name: "Pectra",
    status: "live",
    mainnetTarget: {
      when: {
        year: 2025,
        month: 5,
        day: 7,
      },
      confirmed: true,
    },
    milestones: [
      {
        kind: "mainnet",
        when: {
          year: 2025,
          month: 5,
          day: 7,
        },
        status: "complete",
      },
    ],
    eips: [
      {
        id: 2537,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 2935,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 6110,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7002,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7251,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7549,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7623,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7642,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7685,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7691,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7702,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7840,
        status: "included",
        networking: false,
        decidedAt: null,
      },
    ],
    sourceUrl: "https://forkcast.org/upgrade/pectra",
  },
  fusaka: {
    slug: "fusaka",
    name: "Fusaka",
    status: "live",
    mainnetTarget: {
      when: {
        year: 2025,
        month: 12,
        day: 3,
      },
      confirmed: true,
    },
    milestones: [
      {
        kind: "testnet",
        network: "Holešky",
        when: {
          year: 2025,
          month: 10,
          day: 1,
        },
        status: "complete",
      },
      {
        kind: "testnet",
        network: "Sepolia",
        when: {
          year: 2025,
          month: 10,
          day: 14,
        },
        status: "complete",
      },
      {
        kind: "testnet",
        network: "Hoodi",
        when: {
          year: 2025,
          month: 10,
          day: 28,
        },
        status: "complete",
      },
      {
        kind: "mainnet",
        when: {
          year: 2025,
          month: 12,
          day: 3,
        },
        status: "complete",
      },
    ],
    eips: [
      {
        id: 7594,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7642,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7823,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7825,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7883,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7892,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7910,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7917,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7918,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7934,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7935,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7939,
        status: "included",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7951,
        status: "included",
        networking: false,
        decidedAt: null,
      },
    ],
    sourceUrl: "https://forkcast.org/upgrade/fusaka",
  },
  glamsterdam: {
    slug: "glamsterdam",
    name: "Glamsterdam",
    status: "upcoming",
    mainnetTarget: {
      when: {
        year: 2026,
        quarter: 4,
      },
      confirmed: false,
    },
    milestones: [
      {
        kind: "devnet",
        version: 0,
        when: {
          year: 2026,
          month: 4,
          day: 24,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 1,
        when: {
          year: 2026,
          month: 4,
          day: 29,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 2,
        when: {
          year: 2026,
          month: 4,
          day: 30,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 3,
        when: {
          year: 2026,
          month: 5,
          day: 6,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 4,
        when: {
          year: 2026,
          month: 5,
          day: 22,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 5,
        when: {
          year: 2026,
          month: 6,
          day: 4,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 6,
        when: {
          year: 2026,
          month: 6,
          day: 25,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 7,
        when: {
          year: 2026,
          month: 7,
          day: 14,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 8,
        when: {
          year: 2026,
          month: 8,
          day: 13,
        },
        status: "complete",
      },
      {
        kind: "devnet",
        version: 9,
        when: {
          year: 2026,
          month: 9,
          day: 1,
        },
        status: "live",
      },
      {
        kind: "testnet",
        network: "Platåberget",
        when: {
          year: 2026,
          month: 8,
          day: 13,
        },
        status: "complete",
      },
      {
        kind: "testnet",
        network: "Sepolia",
        when: {
          year: 2026,
          month: 10,
          day: 6,
        },
        status: "anticipated",
      },
      {
        kind: "testnet",
        network: "Hoodi",
        when: {
          year: 2026,
          month: 10,
          day: 26,
        },
        status: "anticipated",
      },
      {
        kind: "mainnet",
        when: {
          year: 2026,
          quarter: 4,
        },
        status: "projected",
      },
    ],
    eips: [
      {
        id: 2780,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
      {
        id: 7688,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
      {
        id: 7708,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 7732,
        status: "scheduled",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7778,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 7843,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 7928,
        status: "scheduled",
        networking: false,
        decidedAt: null,
      },
      {
        id: 7954,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 7975,
        status: "scheduled",
        networking: true,
        decidedAt: null,
      },
      {
        id: 7976,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 7981,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 7997,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
      {
        id: 8024,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 8037,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/236",
          date: "2026-05-07",
        },
      },
      {
        id: 8038,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
      {
        id: 8045,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
      {
        id: 8061,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
      {
        id: 8070,
        status: "scheduled",
        networking: true,
        decidedAt: null,
      },
      {
        id: 8136,
        status: "scheduled",
        networking: true,
        decidedAt: null,
      },
      {
        id: 8159,
        status: "scheduled",
        networking: true,
        decidedAt: null,
      },
      {
        id: 8189,
        status: "scheduled",
        networking: true,
        decidedAt: null,
      },
      {
        id: 8246,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
      {
        id: 8282,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: null,
          date: "2026-08-04",
        },
      },
    ],
    sourceUrl: "https://forkcast.org/upgrade/glamsterdam",
  },
  hegota: {
    slug: "hegota",
    name: "Hegotá",
    status: "planning",
    mainnetTarget: {
      when: {
        year: 2027,
        quarter: 2,
      },
      confirmed: false,
    },
    milestones: [
      {
        kind: "testnet",
        network: "Sepolia",
        when: {
          year: 2027,
        },
        status: "projected",
      },
      {
        kind: "testnet",
        network: "Hoodi",
        when: {
          year: 2027,
        },
        status: "projected",
      },
      {
        kind: "mainnet",
        when: {
          year: 2027,
          quarter: 2,
        },
        status: "projected",
      },
    ],
    eips: [
      {
        id: 7805,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acdc/175",
          date: "2026-02-19",
        },
      },
      {
        id: 8141,
        status: "scheduled",
        networking: false,
        decidedAt: {
          call: "acde/244",
          date: "2026-08-27",
        },
      },
    ],
    sourceUrl: "https://forkcast.org/upgrade/hegota",
  },
} satisfies UpgradeStore
