/**
 * Drift detection test script.
 *
 * Tests the intl-content-tree package's diff engine against real
 * manifests generated by the pipeline. Each test makes ONE isolated
 * change to the English source and verifies the correct drift type.
 *
 * Usage:
 *   npx ts-node -O '{"module":"commonjs"}' src/scripts/i18n/test-drift-detection.ts \
 *     --manifest <path-to-.manifest.json> \
 *     --source <path-to-english-source> \
 *     --format md|json \
 *     [--test <test-name>]  (run one test, or all if omitted)
 *
 * Requires: manifests generated by a pipeline run with intl-content-tree v0.1.1+
 */

import { readFileSync } from "fs"

import { detectDrift, hasEnglishChanged } from "./lib/ai/manifest-adapter"

// ---------------------------------------------------------------------------
// CLI args
// ---------------------------------------------------------------------------

const args = process.argv.slice(2)
let manifestPath = ""
let sourcePath = ""
let format: "markdown" | "json" = "markdown"
let singleTest = ""

for (let i = 0; i < args.length; i++) {
  if (args[i] === "--manifest") manifestPath = args[++i]
  else if (args[i] === "--source") sourcePath = args[++i]
  else if (args[i] === "--format") {
    const f = args[++i]
    format = f === "md" || f === "markdown" ? "markdown" : "json"
  } else if (args[i] === "--test") singleTest = args[++i]
}

if (!manifestPath || !sourcePath) {
  console.log(`
Usage:
  npx ts-node -O '{"module":"commonjs"}' src/scripts/i18n/test-drift-detection.ts \\
    --manifest <path> --source <path> --format md|json [--test <name>]

Tests:
  no-change         Identical source -> all unchanged
  prose-edit        Change a sentence -> translatableDrift
  url-change        Change a link URL -> inertDrift
  heading-label     Change heading text (keep ID) -> labelHashChanged
  section-add       Add a new section -> added
  section-remove    Remove a section -> removed
  section-reorder   Swap two sections -> reordered
  inline-code       Change inline code -> inertDrift
  frontmatter-title Change title -> translatableDrift
  frontmatter-image Change image path -> inertDrift
  json-value-edit   Change a JSON value -> translatableDrift (json only)
  json-key-add      Add a new JSON key -> added (json only)
`)
  process.exit(1)
}

const manifestJson = readFileSync(manifestPath, "utf-8")
const originalSource = readFileSync(sourcePath, "utf-8")

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

interface TestResult {
  name: string
  passed: boolean
  details: string
}

function runTest(
  name: string,
  mutatedSource: string,
  check: (
    changed: boolean,
    drift: ReturnType<typeof detectDrift>
  ) => { passed: boolean; details: string }
): TestResult {
  const changed = hasEnglishChanged(mutatedSource, manifestJson, format)
  const drift = detectDrift(mutatedSource, manifestJson, format)
  const result = check(changed, drift)
  return { name, ...result }
}

function summarizeDrift(drift: ReturnType<typeof detectDrift>): string {
  const parts: string[] = []
  if (drift.unchanged.length) parts.push(`unchanged:${drift.unchanged.length}`)
  if (drift.inertDrift.length)
    parts.push(`inertDrift:${drift.inertDrift.length}`)
  if (drift.translatableDrift.length)
    parts.push(`translatableDrift:${drift.translatableDrift.length}`)
  if (drift.added.length) parts.push(`added:${drift.added.length}`)
  if (drift.removed.length) parts.push(`removed:${drift.removed.length}`)
  if (drift.renamed.length) parts.push(`renamed:${drift.renamed.length}`)
  if (drift.reordered.length) parts.push(`reordered:${drift.reordered.length}`)
  const labelChanges = [
    ...drift.unchanged,
    ...drift.inertDrift,
    ...drift.translatableDrift,
    ...drift.reordered,
  ].filter((e) => e.labelHashChanged).length
  if (labelChanges) parts.push(`labelHashChanged:${labelChanges}`)
  return parts.join(", ")
}

// ---------------------------------------------------------------------------
// Markdown tests
// ---------------------------------------------------------------------------

const mdTests: Record<string, () => TestResult> = {
  "no-change": () =>
    runTest("no-change", originalSource, (changed, drift) => {
      const allUnchanged =
        drift.inertDrift.length === 0 &&
        drift.translatableDrift.length === 0 &&
        drift.added.length === 0 &&
        drift.removed.length === 0 &&
        drift.renamed.length === 0 &&
        drift.reordered.length === 0
      const noLabel = [...drift.unchanged].every((e) => !e.labelHashChanged)
      return {
        passed: !changed && allUnchanged && noLabel,
        details: changed
          ? `FAIL: hasEnglishChanged=true (expected false). Drift: ${summarizeDrift(drift)}`
          : allUnchanged && noLabel
            ? "PASS: no changes detected"
            : `FAIL: expected all unchanged. Got: ${summarizeDrift(drift)}`,
      }
    }),

  "prose-edit": () => {
    // Find the first substantial prose line after frontmatter
    const lines = originalSource.split("\n")
    let editLine = -1
    let inFrontmatter = false
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].trim() === "---") {
        inFrontmatter = !inFrontmatter
        continue
      }
      if (inFrontmatter) continue
      if (
        lines[i].length > 50 &&
        !lines[i].startsWith("#") &&
        !lines[i].startsWith("<") &&
        !lines[i].startsWith("```")
      ) {
        editLine = i
        break
      }
    }
    if (editLine === -1)
      return {
        name: "prose-edit",
        passed: false,
        details: "SKIP: no suitable prose line found",
      }

    const mutated = [...lines]
    mutated[editLine] = mutated[editLine].replace(/\.$/, ". [DRIFT TEST EDIT]")
    return runTest("prose-edit", mutated.join("\n"), (changed, drift) => ({
      passed: changed && drift.translatableDrift.length > 0,
      details:
        changed && drift.translatableDrift.length > 0
          ? `PASS: translatableDrift detected (${drift.translatableDrift.map((e) => e.id).join(", ")}). Full: ${summarizeDrift(drift)}`
          : `FAIL: expected translatableDrift. hasChanged=${changed}, drift: ${summarizeDrift(drift)}`,
    }))
  },

  "url-change": () => {
    const mutated = originalSource.replace(
      /\]\(https?:\/\/[^)]+\)/,
      "](https://example.com/drift-test)"
    )
    if (mutated === originalSource)
      return {
        name: "url-change",
        passed: false,
        details: "SKIP: no external URL found",
      }
    return runTest("url-change", mutated, (changed, drift) => ({
      passed:
        changed &&
        drift.inertDrift.length > 0 &&
        drift.translatableDrift.length === 0,
      details:
        changed &&
        drift.inertDrift.length > 0 &&
        drift.translatableDrift.length === 0
          ? `PASS: inertDrift detected, no translatableDrift. Full: ${summarizeDrift(drift)}`
          : `FAIL: expected only inertDrift. hasChanged=${changed}, drift: ${summarizeDrift(drift)}`,
    }))
  },

  "heading-label": () => {
    // Change heading text but keep {#id}
    const mutated = originalSource.replace(
      /^(#{1,6})\s+(.+?)(\s*\{#[^}]+\})\s*$/m,
      "$1 DRIFT TEST HEADING$3"
    )
    if (mutated === originalSource)
      return {
        name: "heading-label",
        passed: false,
        details: "SKIP: no heading with {#id} found",
      }
    return runTest("heading-label", mutated, (changed, drift) => {
      const hasLabelChange = [
        ...drift.unchanged,
        ...drift.translatableDrift,
        ...drift.reordered,
      ].some((e) => e.labelHashChanged)
      return {
        passed: hasLabelChange,
        details: hasLabelChange
          ? `PASS: labelHashChanged detected. Full: ${summarizeDrift(drift)}`
          : `FAIL: no labelHashChanged. hasChanged=${changed}, drift: ${summarizeDrift(drift)}`,
      }
    })
  },

  "section-add": () => {
    // Add a new h2 section before the last line
    const lines = originalSource.split("\n")
    const insertIdx = Math.max(lines.length - 5, 10)
    lines.splice(
      insertIdx,
      0,
      "",
      "## Drift Test Section {#drift-test-section}",
      "",
      "This is a new section added for testing.",
      ""
    )
    return runTest("section-add", lines.join("\n"), (changed, drift) => ({
      passed:
        changed &&
        drift.added.length > 0 &&
        drift.added.some((e) => e.id === "drift-test-section"),
      details:
        changed && drift.added.length > 0
          ? `PASS: added section detected (${drift.added.map((e) => e.id).join(", ")}). Full: ${summarizeDrift(drift)}`
          : `FAIL: expected added section. hasChanged=${changed}, drift: ${summarizeDrift(drift)}`,
    }))
  },

  "section-remove": () => {
    // Remove the last h2 section (heading + content until EOF or next heading)
    const lines = originalSource.split("\n")
    let lastH2 = -1
    for (let i = lines.length - 1; i >= 0; i--) {
      if (/^## /.test(lines[i])) {
        lastH2 = i
        break
      }
    }
    if (lastH2 === -1)
      return {
        name: "section-remove",
        passed: false,
        details: "SKIP: no h2 section found",
      }
    const mutated = lines.slice(0, lastH2).join("\n")
    return runTest("section-remove", mutated, (changed, drift) => ({
      passed: changed && drift.removed.length > 0,
      details:
        changed && drift.removed.length > 0
          ? `PASS: removed section detected (${drift.removed.map((e) => e.id).join(", ")}). Full: ${summarizeDrift(drift)}`
          : `FAIL: expected removed section. hasChanged=${changed}, drift: ${summarizeDrift(drift)}`,
    }))
  },

  "section-reorder": () => {
    // Find first two h2 sections and swap them
    const lines = originalSource.split("\n")
    const h2Indices: number[] = []
    for (let i = 0; i < lines.length; i++) {
      if (/^## /.test(lines[i])) h2Indices.push(i)
    }
    if (h2Indices.length < 2)
      return {
        name: "section-reorder",
        passed: false,
        details: "SKIP: fewer than 2 h2 sections",
      }

    const sec1Start = h2Indices[0]
    const sec1End = h2Indices[1]
    const sec2Start = h2Indices[1]
    const sec2End = h2Indices.length > 2 ? h2Indices[2] : lines.length

    const before = lines.slice(0, sec1Start)
    const sec1 = lines.slice(sec1Start, sec1End)
    const sec2 = lines.slice(sec2Start, sec2End)
    const after = lines.slice(sec2End)

    const mutated = [...before, ...sec2, ...sec1, ...after].join("\n")
    return runTest("section-reorder", mutated, (changed, drift) => ({
      passed: changed && drift.reordered.length > 0,
      details:
        changed && drift.reordered.length > 0
          ? `PASS: reordered detected (${drift.reordered.map((e) => `${e.id}:${e.oldIndex}->${e.newIndex}`).join(", ")}). Full: ${summarizeDrift(drift)}`
          : `FAIL: expected reordered. hasChanged=${changed}, drift: ${summarizeDrift(drift)}`,
    }))
  },

  "inline-code": () => {
    const mutated = originalSource.replace(/`[^`]+`/, "`DRIFTTEST`")
    if (mutated === originalSource)
      return {
        name: "inline-code",
        passed: false,
        details: "SKIP: no inline code found",
      }
    return runTest("inline-code", mutated, (changed, drift) => ({
      passed: changed && drift.inertDrift.length > 0,
      details: changed
        ? `inertDrift:${drift.inertDrift.length}. Full: ${summarizeDrift(drift)}`
        : `FAIL: hasChanged=false. drift: ${summarizeDrift(drift)}`,
    }))
  },

  "frontmatter-title": () => {
    const mutated = originalSource.replace(
      /^title:.*$/m,
      "title: DRIFT TEST TITLE"
    )
    if (mutated === originalSource)
      return {
        name: "frontmatter-title",
        passed: false,
        details: "SKIP: no title field",
      }
    return runTest("frontmatter-title", mutated, (changed, drift) => ({
      passed: changed && drift.translatableDrift.length > 0,
      details: changed
        ? `translatableDrift:${drift.translatableDrift.length} (${drift.translatableDrift.map((e) => e.id).join(", ")}). Full: ${summarizeDrift(drift)}`
        : `FAIL: hasChanged=false. drift: ${summarizeDrift(drift)}`,
    }))
  },

  "frontmatter-image": () => {
    const mutated = originalSource.replace(
      /^image:.*$/m,
      "image: /images/drift-test.png"
    )
    if (mutated === originalSource)
      return {
        name: "frontmatter-image",
        passed: false,
        details: "SKIP: no image field",
      }
    return runTest("frontmatter-image", mutated, (changed, drift) => ({
      passed:
        changed &&
        drift.inertDrift.length > 0 &&
        drift.translatableDrift.length === 0,
      details: changed
        ? `inertDrift:${drift.inertDrift.length}, translatableDrift:${drift.translatableDrift.length}. Full: ${summarizeDrift(drift)}`
        : `FAIL: hasChanged=false. drift: ${summarizeDrift(drift)}`,
    }))
  },
}

// ---------------------------------------------------------------------------
// JSON tests
// ---------------------------------------------------------------------------

const jsonTests: Record<string, () => TestResult> = {
  "no-change": () =>
    runTest("no-change", originalSource, (changed, drift) => {
      const allUnchanged =
        drift.inertDrift.length === 0 &&
        drift.translatableDrift.length === 0 &&
        drift.added.length === 0 &&
        drift.removed.length === 0
      return {
        passed: !changed && allUnchanged,
        details:
          !changed && allUnchanged
            ? "PASS: no changes detected"
            : `FAIL: hasChanged=${changed}, drift: ${summarizeDrift(drift)}`,
      }
    }),

  "json-value-edit": () => {
    const parsed = JSON.parse(originalSource)
    const firstKey = Object.keys(parsed)[0]
    parsed[firstKey] = "DRIFT TEST VALUE"
    return runTest(
      "json-value-edit",
      JSON.stringify(parsed, null, 2),
      (changed, drift) => ({
        passed: changed && drift.translatableDrift.length > 0,
        details: changed
          ? `translatableDrift:${drift.translatableDrift.length} (${drift.translatableDrift.map((e) => e.id).join(", ")}). Full: ${summarizeDrift(drift)}`
          : `FAIL: hasChanged=false. drift: ${summarizeDrift(drift)}`,
      })
    )
  },

  "json-key-add": () => {
    const parsed = JSON.parse(originalSource)
    parsed["drift-test-new-key"] = "New value for testing"
    return runTest(
      "json-key-add",
      JSON.stringify(parsed, null, 2),
      (changed, drift) => ({
        passed:
          changed &&
          drift.added.length > 0 &&
          drift.added.some((e) => e.id === "drift-test-new-key"),
        details: changed
          ? `added:${drift.added.length} (${drift.added.map((e) => e.id).join(", ")}). Full: ${summarizeDrift(drift)}`
          : `FAIL: hasChanged=false. drift: ${summarizeDrift(drift)}`,
      })
    )
  },
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

const tests = format === "markdown" ? mdTests : jsonTests
const toRun = singleTest ? { [singleTest]: tests[singleTest] } : tests

console.log(`\n=== Drift Detection Tests ===`)
console.log(`Format: ${format}`)
console.log(`Source: ${sourcePath}`)
console.log(`Manifest: ${manifestPath}\n`)

let passed = 0
let failed = 0
let skipped = 0

for (const [name, fn] of Object.entries(toRun)) {
  if (!fn) {
    console.log(`  ? ${name}: UNKNOWN TEST`)
    continue
  }
  const result = fn()
  const icon = result.passed
    ? "+"
    : result.details.startsWith("SKIP")
      ? "~"
      : "x"
  console.log(`  ${icon} ${result.name}: ${result.details}`)
  if (result.details.startsWith("SKIP")) skipped++
  else if (result.passed) passed++
  else failed++
}

console.log(`\n${passed} passed, ${failed} failed, ${skipped} skipped`)
if (failed > 0) process.exit(1)
