// Generated by src/scripts/update-explorers.ts -- do not edit by hand.
// Keys are EIP-3770 chain short names, the prefix a user types before an address.
const explorers = {
  eth: {
    name: "Ethereum Mainnet",
    url: "https://eth.blockscout.com",
    icon: "ethereum.png",
  },
  arb1: {
    name: "Arbitrum One",
    url: "https://arbitrum.blockscout.com",
    icon: "arbitrum.jpg",
  },
  base: {
    name: "Base",
    url: "https://base.blockscout.com",
    icon: "base.png",
  },
  oeth: {
    name: "OP Mainnet",
    url: "https://explorer.optimism.io",
    icon: "optimism.png",
  },
  zksync: {
    name: "zkSync Mainnet",
    url: "https://zksync.blockscout.com",
    icon: "zksyncEra.jpg",
  },
  linea: {
    name: "Linea",
    url: "https://explorer.linea.build",
    icon: "linea.png",
  },
  scr: {
    name: "Scroll",
    url: "https://scroll.blockscout.com",
    icon: "scroll.png",
  },
  unichain: {
    name: "Unichain",
    url: "https://unichain.blockscout.com",
    icon: "unichain.png",
  },
  ink: {
    name: "Ink",
    url: "https://explorer.inkonchain.com",
    icon: "ink.png",
  },
} as const

export default explorers
