name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as PRs are merged
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
[![Release Drafter](https://github.com/lygg6699/ethereum-org-website/actions/workflows/release-drafter.yml/badge.svg?branch=dev)](https://github.com/lygg6699/ethereum-org-website/actions/workflows/release-drafter.yml)
