name: Tests
on:
  pull_request:
    branches: [dev, master, staging]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Unit Tests
        run: pnpm test:unit
